name: Majsoul-Login
on:
  workflow_dispatch:
  schedule: #5:00
   - cron: '0 21 * * *'
jobs:
  login:
    name: Majsoul-Login
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Selenium
        run: pip install selenium==4.17.2

      - name: Majsoul login
        run: python login.py ${{ secrets.EMAIL }} ${{ secrets.PASSWD }}
      
      - name: 'Send mail'
        uses: wwmmzz/action-send-mail@master
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAILUSERNAME }}
          password: ${{ secrets.MAILPASSWORD }}
          subject: Majsoul login
          html_body: file://index.html
          attachments: screenshot.png
          to: ${{ secrets.EMAIL }}
          from: GitHub Actions
